# Site settings
title: shubox.io
email: joel@shubox.io
shuboxScriptId: "03457406"
smallChatId: "123"
production: "false"
baseurl: ""    # the subpath of your site, e.g. /blog
url: ""        # the base hostname & protocol for your site, e.g. http://example.com
description: >
  The easiest and fastest way for your web-app to
  upload images directly to Amazon S3

# Analytics settings
fb_pixel: "1490231254348649"
ga: "UA-80905075-3"
mixpanel: "01357d729eae31357daebaf72ebb3cd6"

# Site-wide defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /blog/:year/:month/:day/:title/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
keep_files:
  - ./js/
  - ./css/
  - ./images/
  - ./favicon.ico

# Collections
collections:
  - examples
  - docs
